scan_filter_chain:
  - name: box_filter
    type: laser_filters/LaserScanBoxFilter
    params:
      box_frame: base_footprint
      min_x: -0.1
      max_x: 0.1
      min_y: -0.3
      max_y: 0.05
      min_z: -0.1
      max_z: 0.1
      invert: false
